services:
  cncloud:
    depends_on:
      - db
    build: .
  admin:
    environment:
      - ADMIN_PANEL_DB_HOST=db
    depends_on:
      - db
    build: adminPanel/
  db:
    environment:
      POSTGRES_USER: cncloud
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cncloud
      PGDATA: /db-data
    image: postgres:18-alpine3.23
    volumes:
      - db-data:/db-data
  nginx:
    build: nginx/
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - admin
      - cncloud
volumes:
  db-data: